function notice(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').style.display='none',2600);}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);notice('已生成下载：'+name);}

$('year').innerHTML=CALENDAR.map(c=>`<option value="${c.year}">${c.year} · ${c.ganZhi}</option>`).join('');
$('year').onchange=e=>selectYear(Number(e.target.value));$('prev').onclick=()=>selectYear(selected-1);$('next').onclick=()=>selectYear(selected+1);
$('rangeStart').oninput=e=>{viewStart=Math.max(YEAR_MIN,Math.min(Number(e.target.value),viewEnd-MIN_SPAN));selected=Math.max(selected,viewStart);render();};
$('rangeEnd').oninput=e=>{viewEnd=Math.min(YEAR_MAX,Math.max(Number(e.target.value),viewStart+MIN_SPAN));selected=Math.min(selected,viewEnd);render();};
$('sensitivity').onclick=e=>{const option=e.target.closest('[data-profile]');if(!option||option.dataset.profile===profile)return;profile=option.dataset.profile;recalc();};
$('chart').onclick=e=>{const rect=$('chart').getBoundingClientRect(),data=visible(),ratio=(e.clientX-rect.left-54)/Math.max(1,rect.width-74),index=Math.round(Math.max(0,Math.min(1,ratio))*(data.length-1));selectYear(data[index].year);};
$('chart').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();selectYear(Math.max(YEAR_MIN,Math.min(YEAR_MAX,selected+(e.key==='ArrowLeft'?-1:1))));}};
$('seriesControls').onchange=e=>{const key=e.target.dataset.series;if(!key)return;series[key]=e.target.checked;if(!Object.values(series).some(Boolean)){series.total=true;notice('至少保留一条趋势');}render();};
$('downloadJson').onclick=()=>download('壬午女命-流年趋势图谱-'+profile+'.json',JSON.stringify(M.exportData(CALENDAR,profile),null,2),'application/json');
$('downloadCsv').onclick=()=>{const head=['年份','虚岁','流年','大运','综合分','事业','财运','感情','贵人机会','open','close','high','low','评分口径'];const rows=all.map(d=>[d.year,d.age,d.ganZhi,d.daYun,d.score,...M.keys.map(k=>d.scores[k]),d.open,d.close,d.high,d.low,M.profiles[profile].label]);download('壬午女命-流年趋势图谱-年度表.csv','\ufeff'+[head,...rows].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');};
$('downloadHtml').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);notice('网址已复制，可直接转发');}catch{prompt('复制这个网址转发：',location.href);}};

$('calendarMethod').innerHTML=`<p>出生信息按你提供的 <strong>2002-12-12 凌晨 04:00–05:00、女命、宁夏固原</strong> 处理。网页建模取区间中点 04:30，但时柱并不依赖这个中点：固原市区经度约 106.24°E，相对东八区中央经线 120°E 的经度差约 −55 分钟；2002-12-12 的方程时约 +6.4 分钟，合并后真太阳时约比北京时间提前 <strong>48 分 38 秒</strong>。因此北京时间 04:00–05:00 约对应真太阳时 03:11–04:11，整个区间都落在寅时。</p><p>按真太阳时排盘，四柱稳定为 <strong>壬午、壬子、甲寅、丙寅</strong>，日主甲木。灵犀排盘给出的起运时间为 <strong>1 年 6 个月 13 天</strong>，约在 2004-06-25 前后进入第一步大运。女命生于阳干壬年，按常用规则逆排：辛亥 → 庚戌 → 己酉 → 戊申 → 丁未 → 丙午 → 乙巳 → 甲辰 → 癸卯 → 壬寅。</p><p>一个流年按立春到下一年立春理解；第一年从出生时开始。本页为独立静态网页，为便于逐年计算，立春日期统一按 2 月 4 日落点表示；交运年则按约 6 月 25 日切分，并按两段覆盖天数加权。年龄采用虚岁标号：公历年份 − 2002 + 1，不是当天周岁。真太阳时的分钟校正用于确认时柱，不把分钟级误差伪装成年度评分的精度。</p>`;
$('rulebook').innerHTML=`<p>每个十神先对应一组基础分，顺序均为 [事业，财运，感情，机会]。十神是其他天干相对甲日主的关系类别；这些系数是本版本公开设定的研究参数，不是古籍规定的标准分值。</p><div class="table-scroll"><table><thead><tr><th>天干与甲日主的关系</th><th>事业</th><th>财运</th><th>感情</th><th>机会</th></tr></thead><tbody>${Object.entries(M.vectors).map(([s,v])=>`<tr><td>${s} · ${M.gods[s]}</td>${v.map(n=>`<td>${sign(n,0)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>一柱中的天干直接出现（透干）占 40%，地支内部所含天干（藏干）合计占 60%。当年（流年）的影响倍率为 1.4，十年阶段（大运）为 1.0。三种评分口径只在这套基础分上增加五行加权：火土调候为火 +6、土 +5、金 −1、水 −5、木 −4；中性参考全部为 0；水木顺势为水 +5、木 +4、金 −3、火 −4、土 −5。它们用于展示“寒湿调候”与“从印顺势”两种判断在年度结果上的敏感度。</p><p>地支内含天干的简化比例：${Object.entries(M.hidden).map(([b,a])=>b+'（'+a.map(([s,w])=>s+Math.round(w*100)+'%').join('、')+'）').join('；')}。这只是本模型采用的统一比例。</p><div class="table-scroll"><table><thead><tr><th>干支互动</th><th>配对与四项影响</th></tr></thead><tbody>${M.relations.map(r=>`<tr><td>${r.name}</td><td>${r.pairs.join('、')} → [${r.v.join(', ')}]</td></tr>`).join('')}<tr><td>自刑（简化）</td><td>辰、午、酉、亥出现同支重复 → [−1, 0, −2, −1]</td></tr><tr><td>天干五合</td><td>甲己、乙庚、丙辛、丁壬、戊癸 → [1, 1, 1, 2]</td></tr></tbody></table></div><p>当年与出生盘各柱的关系按 1 倍计入；大运与出生盘按 0.6 倍；当年与大运按 0.8 倍。若地支关系落到日支，感情项再乘 1.5。同一组干支可能同时存在多种关系，本页允许不同关系叠加，但不会仅凭“冲”就断定坏事，也不判断是否真正合化。甲日主的天乙贵人位取丑、未，当年命中时给机会项 +4。</p><p>固定基准为 50 分，不根据出生条件推测社会起点。所有年份使用同一套公开系数，没有随机数、人工指定峰值或强制制造波动。</p>`;
recalc();
if(typeof ResizeObserver!=='undefined')new ResizeObserver(()=>drawChart(visible(),all[selected-YEAR_MIN])).observe($('chart'));
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'select_life_year',description:'切换流年趋势图谱中的年份并返回当前分数。',inputSchema:{type:'object',properties:{year:{type:'integer',minimum:YEAR_MIN,maximum:YEAR_MAX}},required:['year'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){selectYear(input.year);const d=all[selected-YEAR_MIN];return {year:selected,score:d.score,scores:d.scores,profile};}})).catch(()=>{});}catch{}}