function render(){
 const d=all[selected-YEAR_MIN],data=visible();syncRangeControls();$('year').value=selected;$('prev').disabled=selected===YEAR_MIN;$('next').disabled=selected===YEAR_MAX;
 $('metrics').innerHTML=[['综合指数',d.score,'#ffb454',null],...M.names.map((n,i)=>[n,d.scores[M.keys[i]],colors[i],M.keys[i]])].map(([n,v,col,key])=>{const prev=all[selected-YEAR_MIN-1];const change=prev?v-(key?prev.scores[key]:prev.score):v-50;return `<div class="metric"><div class="metric-name">${n}</div><div class="metric-value" style="color:${col}">${fmt(v)}</div><svg class="metric-line" viewBox="0 0 100 40" preserveAspectRatio="none" aria-hidden="true"><polyline points="${line(data,key,100,40)}" fill="none" stroke="${col}" stroke-width="2"/></svg><div class="metric-change"><span>${selected} · ${d.ganZhi}</span><span class="${tone(change)}">${sign(change)} ${selected===YEAR_MIN?'较基准':'较上年'}</span></div></div>`}).join('');
 renderSeriesControls();drawChart(data,d);renderProfiles();
 $('yearDetail').innerHTML=`<div class="year-head"><strong>${d.ganZhi}年</strong><span>${d.age} 虚岁</span></div><p class="year-sub">十年阶段（大运）：${d.daYun==='童限'?'尚未起运':d.daYun}<br>本流年：${d.period.start.slice(0,10)} — ${d.period.end.slice(0,10)}<br>结束日也是下一流年的起点</p><div class="ohlc">${[['年初承接',d.open],['年度结果',d.close],['图示上界',d.high],['图示下界',d.low]].map(([n,v])=>`<div><span>${n}</span><b>${fmt(v)}</b></div>`).join('')}</div><p class="year-description">综合分 ${fmt(d.score)}，较上年 <span class="${tone(d.change)}">${sign(d.change)}</span>。<br>四项最高与最低相差 ${fmt(Math.max(...Object.values(d.scores))-Math.min(...Object.values(d.scores)))} 分。</p><h3>这一年为什么这样打分</h3>${d.ledger.filter(r=>!['BASE','CAP','ROUND'].includes(r.id)).sort((a,b)=>Math.abs(M.dot(b.vector))-Math.abs(M.dot(a.vector))).slice(0,3).map(r=>`<p class="impact">${impactLabel(r)}<br><span class="${tone(M.dot(r.vector))}">综合影响 ${sign(M.dot(r.vector))}</span></p>`).join('')}${d.period.segments.length>1?'<p class="small-note">这一年正好更换大运，按实际覆盖时间计算：'+d.period.segments.map(s=>s.name+' '+(s.weight*100).toFixed(1)+'%').join(' / ')+'</p>':''}`;
 $('ledgerTitle').textContent=`${selected} ${d.ganZhi} · 评分账本`;
 $('ledger').innerHTML=d.ledger.map(r=>`<tr><td>${friendlyEvidence(r.evidence)}<small>规则 ${r.id}${r.multiplier!=null?' · 本项权重 '+M.round(r.multiplier):''}</small></td>${r.vector.map(v=>`<td class="${tone(v)} numeric">${sign(v,3)}</td>`).join('')}<td class="${tone(M.dot(r.vector))} numeric">${sign(M.dot(r.vector),3)}</td></tr>`).join('');
 $('ledgerTotal').innerHTML=`<tr><td>最终分数 <small>全部规则汇总后保留两位小数</small></td>${M.keys.map(k=>`<td>${fmt(d.scores[k])}</td>`).join('')}<td style="color:var(--amber)">${fmt(d.score)}</td></tr>`;
}

function drawChart(data,d){
 const rect=$('chart').getBoundingClientRect(),w=Math.max(300,rect.width||1000),h=rect.height||410,l=54,r=20,t=42,b=44,pw=w-l-r,ph=h-t-b,step=pw/data.length,[lo,hi]=chartDomain(),x=i=>l+(i+.5)*step,y=n=>t+(hi-n)/(hi-lo)*ph;let s='';
 $('axisDomain').textContent=`纵轴 ${lo}–${hi}`;
 for(let i=0;i<=5;i++){const n=Math.round((lo+(hi-lo)*i/5)*10)/10;s+=`<line x1="${l}" y1="${y(n)}" x2="${w-r}" y2="${y(n)}" stroke="#2e3b49" stroke-dasharray="${Math.abs(n-50)<.01?'6 5':'2 5'}"/><text x="${l-12}" y="${y(n)+5}" fill="#9eb0c4" font-size="14" text-anchor="end">${n}</text>`;}
 let last='';data.forEach((p,i)=>{const name=p.period.segments[p.period.segments.length-1].name;if(name!==last){s+=`<line x1="${x(i)-step/2}" x2="${x(i)-step/2}" y1="24" y2="${h-b}" stroke="#46566a" stroke-dasharray="4 5"/><text x="${x(i)}" y="18" font-size="12" fill="#9cacbf">${name}</text>`;last=name;}});
 const at=data.findIndex(p=>p.year===selected);s+=`<rect x="${x(at)-step/2}" y="30" width="${step}" height="${h-b-30}" fill="#eef5ff" opacity=".055"/><line x1="${x(at)}" x2="${x(at)}" y1="${t}" y2="${h-b}" stroke="#d8e3ef" opacity=".42" stroke-dasharray="4 5"/>`;
 if(series.total)data.forEach((p,i)=>{const col=p.close>=p.open?'#40cc9a':'#f47b80',cw=Math.max(1.5,step*.48);s+=`<g><title>${p.year} ${p.ganZhi}：综合 ${p.score}，${p.daYun}</title><line x1="${x(i)}" x2="${x(i)}" y1="${y(p.high)}" y2="${y(p.low)}" stroke="${col}" stroke-width="1" opacity=".58"/><rect x="${x(i)-cw/2}" y="${y(Math.max(p.open,p.close))}" width="${cw}" height="${Math.max(2,Math.abs(y(p.open)-y(p.close)))}" rx="1" fill="${col}" ${p.year===selected?'stroke="#eef5ff" stroke-width="1.2"':''}/></g>`;});
 M.keys.forEach((key,k)=>{if(!series[key])return;const points=data.map((p,i)=>`${x(i)},${y(p.scores[key])}`).join(' ');s+=`<polyline points="${points}" fill="none" stroke="${colors[k]}" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round" vector-effect="non-scaling-stroke"><title>${M.names[k]}趋势</title></polyline><circle cx="${x(at)}" cy="${y(d.scores[key])}" r="4.2" fill="${colors[k]}" stroke="#0b0f15" stroke-width="2"><title>${selected} ${M.names[k]} ${d.scores[key]}</title></circle>`;});
 data.forEach((p,i)=>{if(i%Math.ceil(data.length/Math.max(4,Math.floor(w/95)))===0)s+=`<text x="${x(i)}" y="${h-15}" fill="#a6b7ca" font-size="14" text-anchor="middle">${p.year}</text>`;});
 if(series.total)s+=`<circle cx="${x(at)}" cy="${y(d.score)}" r="4.5" fill="#eef5ff" stroke="#101820" stroke-width="2"><title>${selected} 综合 ${d.score}</title></circle>`;
 $('chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" aria-label="${data[0].year}至${data.at(-1).year}综合运势 K 线与分项折线">${s}</svg>`;
 $('chartHint').textContent=`${selected} ${d.ganZhi} · 综合 ${fmt(d.score)} · 点击选年 / ← → 切换`;
}

function notice(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').style.display='none',2600);}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);notice('已生成下载：'+name);}

$('year').innerHTML=CALENDAR.map(c=>`<option value="${c.year}">${c.year} · ${c.ganZhi}</option>`).join('');
$('year').onchange=e=>selectYear(Number(e.target.value));$('prev').onclick=()=>selectYear(selected-1);$('next').onclick=()=>selectYear(selected+1);
$('rangeStart').oninput=e=>{viewStart=Math.max(YEAR_MIN,Math.min(Number(e.target.value),viewEnd-MIN_SPAN));selected=Math.max(selected,viewStart);render();};
$('rangeEnd').oninput=e=>{viewEnd=Math.min(YEAR_MAX,Math.max(Number(e.target.value),viewStart+MIN_SPAN));selected=Math.min(selected,viewEnd);render();};
$('sensitivity').onclick=e=>{const option=e.target.closest('[data-profile]');if(!option||option.dataset.profile===profile)return;profile=option.dataset.profile;recalc();};
$('chart').onclick=e=>{const rect=$('chart').getBoundingClientRect(),data=visible(),ratio=(e.clientX-rect.left-54)/Math.max(1,rect.width-74),index=Math.round(Math.max(0,Math.min(1,ratio))*(data.length-1));selectYear(data[index].year);};
$('chart').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();selectYear(Math.max(YEAR_MIN,Math.min(YEAR_MAX,selected+(e.key==='ArrowLeft'?-1:1))));}};
$('seriesControls').onchange=e=>{const key=e.target.dataset.series;if(!key)return;series[key]=e.target.checked;if(!Object.values(series).some(Boolean)){series.total=true;notice('至少保留一条趋势');}render();};
$('downloadJson').onclick=()=>download('乙酉女命-流年趋势图谱-'+profile+'.json',JSON.stringify(M.exportData(CALENDAR,profile),null,2),'application/json');
$('downloadCsv').onclick=()=>{const head=['年份','虚岁','流年','大运','综合分','事业','财运','感情','贵人机会','open','close','high','low','评分口径'];const rows=all.map(d=>[d.year,d.age,d.ganZhi,d.daYun,d.score,...M.keys.map(k=>d.scores[k]),d.open,d.close,d.high,d.low,M.profiles[profile].label]);download('乙酉女命-流年趋势图谱-年度表.csv','\ufeff'+[head,...rows].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');};
$('downloadHtml').onclick=()=>{const doc=document.documentElement.cloneNode(true);doc.querySelector('#toast').style.display='none';doc.querySelector('#saved-state')?.remove();const state=document.createElement('script');state.id='saved-state';state.textContent='window.SAVED_STATE='+JSON.stringify({profile,year:selected,startYear:viewStart,endYear:viewEnd,series})+';';doc.querySelector('head').append(state);download('乙酉女命-流年趋势图谱.html','<!doctype html>\n'+doc.outerHTML,'text/html;charset=utf-8');};

$('calendarMethod').innerHTML=`<p>你提供的四柱为乙酉、癸未、丙辰、丙申，并确认已经校准，本页直接采用，不再做真太阳时换算。按 2005 乙酉年匹配的公历日期为 2005-07-31；因为只给到申时而没有具体分钟，计算起运时暂取申时中点 16:00。</p><p>女命生于阴干乙年，按传统规则大运顺排：甲申 → 乙酉 → 丙戌 → 丁亥 → 戊子 → 己丑 → 庚寅 → 辛卯 → 壬辰 → 癸巳。以申时中点估算，约在出生后 2 年 4 个月 10 天起运，即 2007-12-11 左右。具体出生分钟会轻微改变交运时刻，但通常不改变四柱和大运顺序。</p><p>一个流年从当年立春到下一年立春；第一年从出生时开始。大运约十年更换一次，交运当年按两段实际覆盖天数加权。年龄沿用原项目的虚岁标号：公历年份 − 2005 + 1，不是当天周岁。</p>`;
$('rulebook').innerHTML=`<p>每个十神先对应一组基础分，顺序均为 [事业，财运，感情，机会]。十神是其他天干相对丙日主的关系类别；这些系数是本版本公开设定的研究参数，不是古籍规定的标准分值。</p><div class="table-scroll"><table><thead><tr><th>天干与丙日主的关系</th><th>事业</th><th>财运</th><th>感情</th><th>机会</th></tr></thead><tbody>${Object.entries(M.vectors).map(([s,v])=>`<tr><td>${s} · ${M.gods[s]}</td>${v.map(n=>`<td>${sign(n,0)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>一柱中的天干直接出现（透干）占 40%，地支内部所含天干（藏干）合计占 60%。当年（流年）的影响倍率为 1.4，十年阶段（大运）为 1.0。当前三种评分口径只在这套基础分上增加五行加权：金水调衡为金 +4、水 +6、木 −5、火 −4、土 −2；中性参考全部为 0；木火土补强为金 −4、水 −5、木 +5、火 +4、土 +2。</p><p>地支内含天干的简化比例：${Object.entries(M.hidden).map(([b,a])=>b+'（'+a.map(([s,w])=>s+Math.round(w*100)+'%').join('、')+'）').join('；')}。这只是本模型采用的统一比例。</p><div class="table-scroll"><table><thead><tr><th>干支互动</th><th>配对与四项影响</th></tr></thead><tbody>${M.relations.map(r=>`<tr><td>${r.name}</td><td>${r.pairs.join('、')} → [${r.v.join(', ')}]</td></tr>`).join('')}<tr><td>自刑（简化）</td><td>辰、午、酉、亥出现同支重复 → [−1, 0, −2, −1]</td></tr><tr><td>天干五合</td><td>甲己、乙庚、丙辛、丁壬、戊癸 → [1, 1, 1, 2]</td></tr></tbody></table></div><p>当年与出生盘各柱的关系按 1 倍计入；大运与出生盘按 0.6 倍；当年与大运按 0.8 倍。若地支关系落到日支，感情项再乘 1.5，因为日支在八字中常被用来观察亲密关系。同一组干支可能同时存在多种关系，本页允许不同关系叠加，但不会仅凭“冲”就断定坏事，也不判断是否真正合化。丙日主的天乙贵人位取酉、亥，当年命中时给机会项 +4。</p><p>固定基准为 50 分，不根据出生条件推测社会起点。所有年份使用同一套公开系数，没有随机数、人工指定峰值或强制制造波动。</p>`;
recalc();
if(typeof ResizeObserver!=='undefined')new ResizeObserver(()=>drawChart(visible(),all[selected-YEAR_MIN])).observe($('chart'));
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'select_life_year',description:'切换流年趋势图谱中的年份并返回当前分数。',inputSchema:{type:'object',properties:{year:{type:'integer',minimum:YEAR_MIN,maximum:YEAR_MAX}},required:['year'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){selectYear(input.year);const d=all[selected-YEAR_MIN];return {year:selected,score:d.score,scores:d.scores,profile};}})).catch(()=>{});}catch{}}
