function notice(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').style.display='none',2600);}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);notice('已生成下载：'+name);}
const CUSTOMER_NAME=(document.title.split(' · ')[0]||'客户').trim();

$('year').innerHTML=CALENDAR.map(c=>`<option value="${c.year}">${c.year} · ${c.ganZhi}</option>`).join('');
$('year').onchange=e=>selectYear(Number(e.target.value));$('prev').onclick=()=>selectYear(selected-1);$('next').onclick=()=>selectYear(selected+1);
$('rangeStart').oninput=e=>{viewStart=Math.max(YEAR_MIN,Math.min(Number(e.target.value),viewEnd-MIN_SPAN));selected=Math.max(selected,viewStart);render();};
$('rangeEnd').oninput=e=>{viewEnd=Math.min(YEAR_MAX,Math.max(Number(e.target.value),viewStart+MIN_SPAN));selected=Math.min(selected,viewEnd);render();};
$('sensitivity').onclick=e=>{const option=e.target.closest('[data-profile]');if(!option||option.dataset.profile===profile)return;profile=option.dataset.profile;recalc();};
$('chart').onclick=e=>{const rect=$('chart').getBoundingClientRect(),data=visible(),ratio=(e.clientX-rect.left-54)/Math.max(1,rect.width-74),index=Math.round(Math.max(0,Math.min(1,ratio))*(data.length-1));selectYear(data[index].year);};
$('chart').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();selectYear(Math.max(YEAR_MIN,Math.min(YEAR_MAX,selected+(e.key==='ArrowLeft'?-1:1))));}};
$('seriesControls').onchange=e=>{const key=e.target.dataset.series;if(!key)return;series[key]=e.target.checked;if(!Object.values(series).some(Boolean)){series.total=true;notice('至少保留一条趋势');}render();};
$('downloadJson').onclick=()=>download(`${CUSTOMER_NAME}-人生K线-${profile}.json`,JSON.stringify(M.exportData(CALENDAR,profile),null,2),'application/json');
$('downloadCsv').onclick=()=>{const head=['年份','虚岁','流年','大运','综合分','事业','财运','感情','贵人','open','close','high','low','评分口径'];const rows=all.map(d=>[d.year,d.age,d.ganZhi,d.daYun,d.score,...M.keys.map(k=>d.scores[k]),d.open,d.close,d.high,d.low,M.profiles[profile].label]);download(`${CUSTOMER_NAME}-人生K线-年度表.csv`,'\ufeff'+[head,...rows].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');};
$('downloadHtml').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);notice(location.protocol==='file:'?'已复制本地文件地址；该地址仅在当前电脑有效':'网址已复制');}catch{prompt('复制当前地址：',location.href);}};

$('calendarMethod').innerHTML=`<p>当前母版中的示例数据按 <strong>2002-12-12 凌晨 04:00–05:00、女命、宁夏固原</strong> 处理。生成新客户时必须先替换为该客户重新计算后的真太阳时、四柱、大运和交运信息，不能直接沿用示例值。</p><p>示例盘按真太阳时排盘，四柱为 <strong>壬午、壬子、甲寅、丙寅</strong>，日主甲木；起运约 1 年 6 个月 13 天，逆排大运。流年以立春为界；交运年按两段覆盖天数加权。</p><p>真太阳时用于确认时柱，不把分钟级误差伪装成年度评分精度。正式客户版本应在生成前完成经度差与方程时校正。</p>`;
$('rulebook').innerHTML=`<p>每个十神对应一组基础分，顺序均为 [事业，财运，感情，贵人]。这些系数是本版本公开设定的研究参数，不是古籍规定的标准分值。</p><div class="table-scroll"><table><thead><tr><th>天干与日主的关系</th><th>事业</th><th>财运</th><th>感情</th><th>贵人</th></tr></thead><tbody>${Object.entries(M.vectors).map(([s,v])=>`<tr><td>${s} · ${M.gods[s]}</td>${v.map(n=>`<td>${sign(n,0)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>一柱中的天干直接出现（透干）占 40%，地支内部所含天干（藏干）合计占 60%。流年的影响倍率为 1.4，大运为 1.0。三种评分口径只在基础分上增加五行加权，用于展示不同身强弱与五行取用判断对年度结果的敏感度。</p><p>地支内含天干的简化比例：${Object.entries(M.hidden).map(([b,a])=>b+'（'+a.map(([s,w])=>s+Math.round(w*100)+'%').join('、')+'）').join('；')}。</p><div class="table-scroll"><table><thead><tr><th>干支互动</th><th>配对与四项影响</th></tr></thead><tbody>${M.relations.map(r=>`<tr><td>${r.name}</td><td>${r.pairs.join('、')} → [${r.v.join(', ')}]</td></tr>`).join('')}<tr><td>自刑（简化）</td><td>辰、午、酉、亥出现同支重复 → [−1, 0, −2, −1]</td></tr><tr><td>天干五合</td><td>甲己、乙庚、丙辛、丁壬、戊癸 → [1, 1, 1, 2]</td></tr></tbody></table></div><p>流年与出生盘各柱的关系按 1 倍计入；大运与出生盘按 0.6 倍；流年与大运按 0.8 倍。若地支关系落到日支，感情项再乘 1.5。同一组干支允许不同关系叠加，但不会仅凭“冲”就断定坏事，也不判断是否真正合化。</p><p>固定基准为 50 分，不根据出生条件推测社会起点。所有年份使用同一套公开系数，没有随机数、人工指定峰值或强制制造波动。</p>`;
recalc();
if(typeof ResizeObserver!=='undefined')new ResizeObserver(()=>drawChart(visible(),all[selected-YEAR_MIN])).observe($('chart'));
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'select_life_year',description:'切换流年趋势图谱中的年份并返回当前分数。',inputSchema:{type:'object',properties:{year:{type:'integer',minimum:YEAR_MIN,maximum:YEAR_MAX}},required:['year'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){selectYear(input.year);const d=all[selected-YEAR_MIN];return {year:selected,score:d.score,scores:d.scores,profile};}})).catch(()=>{});}catch{}}
