function annualAdvice(p){
 const ranked=SCORE_KEYS.map(k=>[k,p.scores[k]]).sort((a,b)=>b[1]-a[1]),best=SCORE_NAMES[ranked[0][0]],weak=SCORE_NAMES[ranked[ranked.length-1][0]];
 const base=(p.reason||'').replace(/[。！？.!?]+$/,'');
 if(p.score>=70)return `${base}，这一年更适合把主动权放在${best}相关事项上，重要计划可以顺势推进并适度提高目标，但仍要给${weak}保留缓冲空间，避免因为整体顺利而忽略局部失衡。`;
 if(p.score<50)return `${base}，这一年更适合先守住已有成果和日常节奏，把有限精力集中到相对更稳的${best}上，涉及${weak}的重要决定尽量延后复核，少做高成本、难回头的冒进选择。`;
 return `${base}，这一年适合以稳定推进为主，把主要精力放在更有支撑的${best}上，同时提前处理${weak}可能带来的摩擦与消耗，在不打乱长期节奏的前提下逐步扩大有效积累。`;
}
function renderGuide(p){const defs=[['total','综合 K 线','#dbe6f3',p.score,'把事业、财运、感情、贵人四项按权重合成为一个年度总指数；K 线实体用于看节奏，短影线只作视觉辅助，不单独解读。'],['career','事业',SCORE_COLORS.career,p.scores.career,'观察学习、工作推进、职位责任、项目执行与个人输出的相对顺逆，强调“做事是否容易形成结果”。'],['wealth','财运',SCORE_COLORS.wealth,p.scores.wealth,'观察收入积累、资源调度、成本压力与财富承载感，不等同于投资收益率，也不作为买卖信号。'],['relationship','感情',SCORE_COLORS.relationship,p.scores.relationship,'观察亲密关系、人际互动、情绪磨合与关系稳定度，数值高低表示相对顺畅程度而非事件必然发生。'],['opportunity','贵人',SCORE_COLORS.opportunity,p.scores.opportunity,'观察外部助力、人脉支持、被看见与获得帮助的窗口；“贵人”强调可借力程度，不代表一定出现某个特定人物。']];$('seriesGuide').innerHTML=defs.map(([k,n,c,v,desc])=>`<article class="guide-item" style="--c:${c}"><div class="guide-head"><div class="guide-name"><span class="guide-dot"></span>${n}</div><div class="guide-score">${Math.round(v*10)/10}</div></div><p>${desc}</p><div class="guide-foot">当前选中：${p.year} · ${p.ganZhi}</div></article>`).join('')}
function renderDetail(p){$('yearDetail').innerHTML=`<div class="detail-score"><div class="big ${scoreClass(p.score)}">${p.score}</div><div class="year">${p.year} · ${p.ganZhi}</div><div class="small">${p.age}岁 · ${p.daYun}</div></div><div><div class="detail-meta">${SCORE_KEYS.map(k=>`<div class="mini"><span>${SCORE_NAMES[k]}</span><b style="color:${SCORE_COLORS[k]}">${p.scores[k]}</b></div>`).join('')}</div><div class="reason"><span class="advice-label">年度建议</span>${annualAdvice(p)}</div></div>`;renderGuide(p);document.querySelectorAll('#tbody tr').forEach(tr=>tr.classList.toggle('selected',+tr.dataset.year===p.year))}
function selectYear(year,scrollDetail){selectedYear=year;const p=PTS.find(x=>x.year===year);if(!p)return;renderDetail(p);scheduleChart();if(scrollDetail&&window.innerWidth<700){$('yearDetail').scrollIntoView({behavior:'smooth',block:'nearest'})}}
$('seriesControls').addEventListener('click',e=>{const b=e.target.closest('.series-toggle');if(!b)return;const key=b.dataset.series;series[key]=!series[key];if(!Object.values(series).some(Boolean))series.total=true;renderSeriesControls();scheduleChart()});
const stage=$('chartStage'),pointers=new Map();
let gesture={mode:null,startStart:1,startEnd:100,startX:0,startY:0,startDist:0,anchorAge:50,anchorFrac:.5,moved:false,lastTap:0,lastTapX:0};
const pDist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),stageFrac=x=>clamp((x-stage.getBoundingClientRect().left)/Math.max(1,stage.getBoundingClientRect().width),0,1);
function selectByClientX(clientX){const frac=stageFrac(clientX),span=viewEnd-viewStart+1,targetAge=viewStart+frac*(span-1);let best=PTS[0],bestD=Infinity;for(const p of PTS){const d=Math.abs(p.age-targetAge);if(d<bestD){best=p;bestD=d}}selectYear(best.year,false)}
function resetGestureFromPointers(){const pts=[...pointers.values()];if(pts.length>=2){const a=pts[0],b=pts[1],midX=(a.x+b.x)/2,frac=stageFrac(midX),span=viewEnd-viewStart+1;gesture.mode='pinch';gesture.startDist=Math.max(8,pDist(a,b));gesture.startStart=viewStart;gesture.startEnd=viewEnd;gesture.anchorFrac=frac;gesture.anchorAge=viewStart+frac*(span-1);gesture.moved=true;stage.classList.add('is-gesturing')}else if(pts.length===1){const a=pts[0];gesture.mode='pan';gesture.startX=a.x;gesture.startY=a.y;gesture.startStart=viewStart;gesture.startEnd=viewEnd;gesture.moved=false;stage.classList.add('is-gesturing')}else{gesture.mode=null;stage.classList.remove('is-gesturing')}}
stage.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;stage.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,type:e.pointerType});resetGestureFromPointers();e.preventDefault()},{passive:false});
stage.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,type:e.pointerType});const pts=[...pointers.values()];if(pts.length>=2&&gesture.mode==='pinch'){const a=pts[0],b=pts[1],d=Math.max(8,pDist(a,b)),scale=d/gesture.startDist,currentFrac=stageFrac((a.x+b.x)/2),startSpan=gesture.startEnd-gesture.startStart+1,newSpan=clamp(startSpan/Math.pow(scale,1.08),MIN_SPAN,MAX_SPAN),s=gesture.anchorAge-currentFrac*(newSpan-1);normalizeView(s,s+newSpan-1);scheduleChart();e.preventDefault();return}if(pts.length===1&&gesture.mode==='pan'){const a=pts[0],dx=a.x-gesture.startX,dy=a.y-gesture.startY;if(Math.abs(dx)>2||Math.abs(dy)>2)gesture.moved=true;const span=gesture.startEnd-gesture.startStart+1,shift=-dx/Math.max(1,stage.getBoundingClientRect().width)*span;normalizeView(gesture.startStart+shift,gesture.startEnd+shift);scheduleChart();e.preventDefault()}},{passive:false});
function endPointer(e){if(!pointers.has(e.pointerId))return;const pt=pointers.get(e.pointerId);pointers.delete(e.pointerId);try{stage.releasePointerCapture?.(e.pointerId)}catch(_){ }const wasTap=!gesture.moved&&gesture.mode==='pan';if(!pointers.size){const now=performance.now();if(wasTap&&now-gesture.lastTap<285&&Math.abs((pt?.x||0)-gesture.lastTapX)<32){viewStart=1;viewEnd=100;scheduleChart();gesture.lastTap=0;gesture.lastTapX=0}else if(wasTap){selectByClientX(pt?.x||e.clientX);gesture.lastTap=now;gesture.lastTapX=pt?.x||e.clientX}gesture.mode=null;stage.classList.remove('is-gesturing')}else resetGestureFromPointers();e.preventDefault()}
stage.addEventListener('pointerup',endPointer,{passive:false});stage.addEventListener('pointercancel',endPointer,{passive:false});stage.addEventListener('lostpointercapture',e=>{if(pointers.has(e.pointerId)){pointers.delete(e.pointerId);resetGestureFromPointers()}});['selectstart','dragstart','contextmenu'].forEach(type=>stage.addEventListener(type,e=>e.preventDefault(),{passive:false}));
stage.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)<0.01)return;e.preventDefault();const span=viewEnd-viewStart+1,frac=stageFrac(e.clientX),anchorAge=viewStart+frac*(span-1),factor=Math.exp(e.deltaY*0.00165),newSpan=clamp(span*factor,MIN_SPAN,MAX_SPAN);setViewAround(anchorAge,newSpan,frac)},{passive:false});
const klineSection=$('klineSection'),fullscreenBtn=$('fullscreenBtn'),fullscreenClose=$('fullscreenClose');let screenMode=false;
async function enterKlineScreen(){if(screenMode)return;screenMode=true;document.body.classList.add('kline-screen-lock');klineSection.classList.add('kline-screen','real-landscape');try{if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen({navigationUI:'hide'})}catch(_){ }setTimeout(scheduleChart,100)}
async function exitKlineScreen(fromFullscreenEvent=false){if(!screenMode)return;screenMode=false;klineSection.classList.remove('pseudo-landscape','real-landscape','kline-screen');document.body.classList.remove('kline-screen-lock');if(!fromFullscreenEvent&&document.fullscreenElement){try{await document.exitFullscreen()}catch(_){ }}setTimeout(scheduleChart,80)}
fullscreenBtn.addEventListener('click',enterKlineScreen);fullscreenClose.addEventListener('click',()=>exitKlineScreen(false));document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&screenMode)exitKlineScreen(true)});window.addEventListener('resize',scheduleChart,{passive:true});
function renderDecades(){const boxes=[];for(let s=1;s<=100;s+=10){const a=PTS.filter(p=>p.age>=s&&p.age<=s+9),m=Math.round(mean(a.map(p=>p.score)));boxes.push(`<div class="decade"><b>${m}</b><span>${s}–${Math.min(s+9,100)}岁</span><span>${a[0].year}–${a[a.length-1].year}</span><div class="bar"><i style="width:${clamp(m,0,100)}%"></i></div></div>`)}$('decades').innerHTML=boxes.join('')}
function renderRanks(){const top=[...PTS].sort((a,b)=>b.score-a.score||b.high-a.high).slice(0,5),bot=[...PTS].sort((a,b)=>a.score-b.score||a.low-b.low).slice(0,5);$('topRank').innerHTML=top.map((p,i)=>`<div class="rank"><span>${i+1}. ${p.year} ${p.ganZhi}<br><small style="color:#718095">${p.age}岁 · ${p.daYun}</small></span><strong class="good">${p.score}</strong></div>`).join('');$('bottomRank').innerHTML=bot.map((p,i)=>`<div class="rank"><span>${i+1}. ${p.year} ${p.ganZhi}<br><small style="color:#718095">${p.age}岁 · ${p.daYun}</small></span><strong class="bad">${p.score}</strong></div>`).join('')}
function renderProfiles(){const fields=[['命局总评','summary','summaryScore'],['性格','personality','personalityScore'],['事业','industry','industryScore'],['财富','wealth','wealthScore'],['感情','marriage','marriageScore'],['家庭','family','familyScore']];$('profiles').innerHTML=fields.map(([t,k,s])=>`<article class="profile"><h3>${t}</h3><div class="scoreline"><b>${DATA[s]}</b><div class="scorebar"><i style="width:${DATA[s]*10}%"></i></div><span style="font-size:10px;color:#718095">/10</span></div><p>${DATA[k]}</p></article>`).join('')}
function renderLedger(){const q=$('search').value.trim().toLowerCase(),f=$('scoreFilter').value,rows=PTS.filter(p=>{const text=`${p.year}${p.ganZhi}${p.daYun}${p.age}`.toLowerCase(),qok=!q||text.includes(q),fok=f==='all'||(f==='high'&&p.score>=70)||(f==='mid'&&p.score>=50&&p.score<70)||(f==='low'&&p.score<50);return qok&&fok});$('tbody').innerHTML=rows.map(p=>`<tr data-year="${p.year}"><td>${p.age}</td><td><b>${p.year}</b></td><td>${p.ganZhi}</td><td>${p.daYun}</td><td class="${scoreClass(p.score)}">${p.score}</td><td>O${p.open} / H${p.high} / L${p.low} / C${p.close}</td><td style="color:#9eabb9">${annualAdvice(p)}</td></tr>`).join('');$('tbody').querySelectorAll('tr').forEach(tr=>tr.addEventListener('click',()=>selectYear(+tr.dataset.year,true)))}
$('search').addEventListener('input',renderLedger);$('scoreFilter').addEventListener('change',renderLedger);renderSeriesControls();renderDecades();renderRanks();renderProfiles();renderLedger();selectYear(current.year,false);
